-- Trigger kiểm tra lương và tuổi khi thêm nhân viên
DROP TRIGGER IF EXISTS trg_Insert_NHANVIEN;
GO
CREATE TRIGGER trg_Insert_NHANVIEN
ON NHANVIEN
FOR INSERT
AS
BEGIN
    DECLARE @Luong FLOAT, @NgSinh DATE, @Tuoi INT
    SELECT @Luong = LUONG, @NgSinh = NGSINH FROM INSERTED
    SET @Tuoi = YEAR(GETDATE()) - YEAR(@NgSinh)
    IF (@Luong <= 15000)
    BEGIN
        RAISERROR(N'Lương phải > 15000', 16, 1)
        ROLLBACK TRANSACTION
        RETURN
    END
    IF (@Tuoi < 18 OR @Tuoi > 65)
    BEGIN
        RAISERROR(N'Tuổi phải nằm trong khoảng từ 18 đến 65', 16, 1)
        ROLLBACK TRANSACTION
        RETURN
    END
END
GO
-- Thêm nhân viên sai tuổi
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES (N'Lê', N'Thị', N'Bé', '013', '2010-01-01', N'123 Lê Lợi, HCM', N'Nữ', 20000, '005', 1)

-- Trigger cấm cập nhật nhân viên ở TP HCM
DROP TRIGGER IF EXISTS trg_Update_NHANVIEN;
GO
CREATE TRIGGER trg_Update_NHANVIEN
ON NHANVIEN
FOR UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT * FROM INSERTED
        WHERE DCHI LIKE N'%TP HCM%'
    )
    BEGIN
        RAISERROR(N'Không được cập nhật nhân viên ở TP HCM', 16, 1)
        ROLLBACK TRANSACTION
    END
END
GO
-- Thử cập nhật nhân viên ở TP HCM
UPDATE NHANVIEN
SET LUONG = 30000
WHERE DCHI LIKE N'%TP HCM%'

-- AFTER INSERT: Đếm nhân viên nam/nữ sau khi thêm
DROP TRIGGER trg_AfterInsert_NHANVIEN;
GO
CREATE TRIGGER trg_AfterInsert_NHANVIEN
ON NHANVIEN
AFTER INSERT
AS
BEGIN
    DECLARE @SoNam INT, @SoNu INT
    SELECT @SoNam = COUNT(*) FROM NHANVIEN WHERE PHAI = N'Nam'
    SELECT @SoNu = COUNT(*) FROM NHANVIEN WHERE PHAI = N'Nữ'
    PRINT N'Tổng số nhân viên Nam: ' + CAST(@SoNam AS NVARCHAR)
    PRINT N'Tổng số nhân viên Nữ: ' + CAST(@SoNu AS NVARCHAR)
END
GO
-- AFTER UPDATE: Nếu cột PHAI được cập nhật thì đếm lại
DROP TRIGGER IF EXISTS trg_AfterUpdate_GioiTinh;
GO
CREATE TRIGGER trg_AfterUpdate_GioiTinh
ON NHANVIEN
AFTER UPDATE
AS
BEGIN
    IF UPDATE(PHAI)
    BEGIN
        DECLARE @SoNam INT, @SoNu INT
        SELECT @SoNam = COUNT(*) FROM NHANVIEN WHERE PHAI = N'Nam'
        SELECT @SoNu = COUNT(*) FROM NHANVIEN WHERE PHAI = N'Nữ'
        PRINT N'Cập nhật giới tính xong.'
        PRINT N'Tổng số nhân viên Nam: ' + CAST(@SoNam AS NVARCHAR)
        PRINT N'Tổng số nhân viên Nữ: ' + CAST(@SoNu AS NVARCHAR)
    END
END
GO
-- Cập nhật giới tính từ Nam thành Nữ
UPDATE NHANVIEN
SET PHAI = N'Nữ'
WHERE MANV = '100';

-- AFTER DELETE ON DEAN: Đếm số đề án mỗi nhân viên đã làm
DROP TRIGGER IF EXISTS trg_AfterDelete_DEAN;
GO
CREATE TRIGGER trg_AfterDelete_DEAN
ON DEAN
AFTER DELETE
AS
BEGIN
    SELECT MA_NVIEN, COUNT(*) AS SoDeAn
    FROM PHANCONG
    GROUP BY MA_NVIEN
END
GO
--
SELECT * FROM PHANCONG;
SELECT * FROM DEAN;
DELETE FROM DEAN WHERE MADA = 1;

-- INSTEAD OF DELETE on NHANVIEN: Xóa luôn thân nhân liên quan
DROP TRIGGER IF EXISTS trg_Delete_NHANVIEN;
GO
CREATE TRIGGER trg_Delete_NHANVIEN
ON NHANVIEN
INSTEAD OF DELETE
AS
BEGIN
    DELETE FROM THANNHAN
    WHERE MA_NVIEN IN (SELECT MANV FROM DELETED)
    DELETE FROM NHANVIEN
    WHERE MANV IN (SELECT MANV FROM DELETED)
END
GO
-- TEST 
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES (N'Hoàng', N'Thị', N'Lan', '999', '1990-01-01', N'Hà Nội', N'Nữ', 20000, '005', 1);
INSERT INTO THANNHAN (MA_NVIEN, TENTN, PHAI, NGSINH, QUANHE)
VALUES ('999', N'Lan Anh', N'Nữ', '2010-01-01', N'Con');
DELETE FROM NHANVIEN WHERE MANV = '999';
SELECT * FROM NHANVIEN WHERE MANV = '999';    
SELECT * FROM THANNHAN WHERE MA_NVIEN = '999';     

-- INSTEAD OF INSERT: Phân công nhân viên làm đề án MADA = 1
DROP TRIGGER IF EXISTS trg_Insert_NHANVIEN_PhancCong;
GO
CREATE TRIGGER trg_Insert_NHANVIEN_PhancCong
ON NHANVIEN
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
    SELECT HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG
    FROM INSERTED
    INSERT INTO PHANCONG (MA_NVIEN, MADA, THOIGIAN)
    SELECT MANV, 1, 10
    FROM INSERTED
END
GO
-- Thêm nhân viên mới và kiểm tra tự động phân công
INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
VALUES (N'Trần', N'Văn', N'Tùng', '102', '1994-04-04', N'Đà Nẵng', N'Nam', 23000, '009', 2);
-- Kiểm tra PHANCONG
SELECT * FROM PHANCONG WHERE MA_NVIEN = '102';


