/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.cafe.ui.component;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;
import poly.cafe.dao.ChiTietKhuVucDAO;
import poly.cafe.dao.KhuVucDAO;
import poly.cafe.dao.impl.ChiTietKhuVucDAOImpl;
import poly.cafe.dao.impl.KhuVucDAOImpl;
import poly.cafe.entity.ChiTietKhuVuc;
import poly.cafe.entity.KhuVuc;
import poly.cafe.ui.manager.ChiTietKhuVucJDialog;
import poly.cafe.ui.component.controller.QuanLyKhuVucController;

/**
 *
 * @author admin
 */
public class QuanLyKhuVuc extends javax.swing.JPanel implements QuanLyKhuVucController{
ChiTietKhuVucDAO dao = new ChiTietKhuVucDAOImpl();
private Frame owner;
    /**
     * Creates new form QLKV
     */
public QuanLyKhuVuc() {
    this(null);
}
    public QuanLyKhuVuc(Frame owner) {
    this.owner = owner;
    initComponents();
    open();
}
private void loadKhuVuc() {
    KhuVucDAO dao = new KhuVucDAOImpl();
    List<KhuVuc> khuVucs = dao.findAll();
    pnlKhuVuc.removeAll();
    khuVucs.forEach(kv -> pnlKhuVuc.add(this.createButton(kv)));
    pnlKhuVuc.revalidate();
    pnlKhuVuc.repaint();
}

private JButton createButton(KhuVuc khuVuc) {
    JButton btn = new JButton();
    btn.setText(khuVuc.getTenKhuVuc());
    btn.setPreferredSize(new Dimension(120, 80));
    btn.setBackground(Color.LIGHT_GRAY);
    btn.setActionCommand(String.valueOf(khuVuc.getKhuVucId()));
    btn.addActionListener((ActionEvent e) -> {
        int khuVucId = Integer.parseInt(e.getActionCommand());
        // ✅ Gọi showChiTietKhuVucDialog
        this.showChiTietKhuVucDialog(khuVucId);
    });
    return btn;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKhuVuc = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        pnlKhuVuc.setLayout(new java.awt.GridLayout(0, 6, 5, 5));

        jButton1.setText("Quản lý khu vực");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKhuVuc, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnlKhuVuc;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        this.loadKhuVuc();
    }
@Override
public void showChiTietKhuVucDialog(int khuVucId) {
    ChiTietKhuVucDAO dao = new ChiTietKhuVucDAOImpl();
    
    // Load danh sách chi tiết khu vực theo khuVucId
    List<ChiTietKhuVuc> dsChiTiet = dao.findByKhuVucId(khuVucId);
    
    // Mở dialog quản lý chi tiết khu vực
    ChiTietKhuVucJDialog dialog = new ChiTietKhuVucJDialog(owner, true);
    dialog.setTitle("Chi tiết khu vực: " + khuVucId);
//    dialog.setKhuVucId(khuVucId);
//    dialog.setChiTietList(dsChiTiet);
    dialog.setVisible(true);
}

}
